extends:
  - airbnb
  - plugin:flowtype/recommended
parser: babel-eslint
plugins:
  - react-native
  - jsx-a11y
  - import
  - flowtype
rules:
  semi: [warn, never]
  no-use-before-define: off
  # React Native does not support *.jsx extension at all
  react/jsx-filename-extension: off
  react-native/no-unused-styles: 2
  react-native/split-platform-components: 2
  react-native/no-inline-styles: 2
  react-native/no-color-literals: 2
